posts/urls.py
from django.urls import path
from .import views
app_name="posts"
from .feeds import LatestPostsFeed

urlpatterns=[
    #path("",views.home,name="home"),
    # path("",views.PostListView.as_view() ,name="posts"),posts
path("<int:year>/<int:month>/<int:day>/<slug:post>",views.post_detail,name="post_detail"),
    path("<int:post_id>/share/",views.post_share,name="post_share"),
    path("<int:id>/comment/",views.post_comment,name="comment"),
    path("tag/<slug:tag_slug>/",views.post_list,name="post_list_by_tag"),
    path("",views.post_list,name="post_list"),
    path("feed/",LatestPostsFeed(),name="post_feed"),
    path('search/',views.post_search,name='post_search')
]

thursBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from posts.sitemaps import PostSitemap


sitemaps = {
    "posts":PostSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/",include("posts.urls")),
    path("sitemap.xml",sitemap,{"sitemaps":sitemaps},name="django.contrib.sitemaps.views.sitemap"),
]

posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import  TaggableManager

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
      return  super().get_queryset().filter(status=Post.Status.PUBLISHED)
class Post(models.Model):
    class Status(models.TextChoices):
        PUBLISHED = 'PB','published'
        DRAFT = 'DF'
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    title = models.CharField (max_length=100)
    slug = models.SlugField(max_length = 100,unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices = Status.choices,
        default = Status.DRAFT,
    )

    objects = models.Manager()
    published = PublishedManager()
    class Meta:
        ordering = ['-publish']
        indexes=[models.Index(fields=['-publish'])]

    def __str__(self):
            return self.title

    def get_absolute_url(self):


        return reverse ("posts:post_detail",args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])
    tags = TaggableManager()



class Comment (models.Model):
       post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
       name = models.CharField(max_length=80)
       email = models.EmailField()
       body = models.TextField()
       created = models.DateTimeField(auto_now_add=True)
       updated = models.DateTimeField(auto_now=True)
       active = models.BooleanField(default=True)

       class Meta:
           ordering = ['created']
           indexes = [models.Index(fields=['created'])]
           def __str__(self):
                return f"Comment by {self.name} on {self.post}"

posts/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','body']


class SearchForm(forms.Form):
    query = forms.CharField()

posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.http import Http404
from django.core.paginator import Paginator,EmptyPage
from django.views.generic import ListView
from .forms import EmailPostForm,CommentForm,SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector,SearchQuery,TrigramSimilarity

# Create your views here.

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = "posts"
#     paginate_by = 3
#     template_name= "posts/posts.html"
def post_list(request, tag_slug=None):

    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        post_list=Post.published.all(tags__in=[tag])
    #PAGINATION WITH THREE PAGEA
    paginator = Paginator(post_list,3)
    page_number = request.GET.get("page",1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,"posts/posts.html",{"posts":posts,"tag":tag})

def post_detail(request, post, year, month, day):

   post  =get_object_or_404(Post,status=Post.Status.PUBLISHED,
                           slug=post,
                            publish__year=year,
                            publish__month=month,
                            publish__day=day
                            )
   comments = post.comments.filter(active=True)
   form = CommentForm()
   print(form.errors)
   #list of dimilar posts

   post_tags_ids = post.tags.values_list('id',flat=True)
   similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
   similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

   return render(request,"posts/post_detail.html",{"post":post,"form":form,"comments":comments,"similar_posts":similar_posts})


def post_share(request,post_id):
    post = get_object_or_404(Post,id=post_id,status=Post.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            #send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject,message,'canyanwu625@gmail.com',[cd['to']])
            sent = True

    else:
        form = EmailPostForm()
        return render(request,'posts/share.html',{"post":post,"form":form,"sent":sent})
#retrieve post by id

@require_POST
def post_comment(request,post_id):
    post = get_object_or_404(Post,id=post_id,status=Post.Status.PUBLISHED)
    comment  = None
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            form = CommentForm()
        return render(request, "posts/comment.html", {"post":post, "form":form, "comment":comment})



def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title',weight='A') + SearchVector('body',weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title',query),
            ).filter(similarity__gt=0.1).order_by('-similarity')

    # Render the form in all cases
    return render(request, 'posts/search.html', {'form': form, 'query': query, 'results': results})

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block tile %}  Add  a comment {% endblock %}

{% block content %}
{% if comment %}

    <h2>Your comment has been added</h2>
    <a href="{{ post.get_absolute_url }}">Back to Post</a>
    {% else %}

    {% include "post/comment_form.html" %}
    {% endif %}

{% endblock %}

posts/templates/posts/includes/comment_form.html
{% extends 'base.html' %}

<h2>Add a new comment </h2>
<form action="{% url "posts:post_comment" post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add comment">
</form>

posts/templates/posts/latest_posts.html
<ul>

    {% for post in latest_post %}
        <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load blog_tags %}


{% block title %} {{ post.title }}{% endblock %}




{% block content %}
<h1>{{ post.title }}</h1>

    <p class="date">
    Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
    <a href="{% url "posts:post_share" post.id %} ">Share Post</a>
    </p>
    <h2>Similar Posts</h2>
    {% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    There are no similar posts
    {% endfor %}

    {% with  comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}</h2>

    {% endwith %}
    {% for comment in comments %}
    <div class="comment">

        <p class="info">
    Comment {{ forloop.counter  }} by {{ comment.name }} on {{ comment.created }}
    {{ comment.body|linebreaks}}
            </p>

    </div>
    {% empty %}
<p>There are no comments</p>
    {% endfor %}
{% include 'posts/includes/comment_form.html' %}
{% endblock %}

posts/templates/posts/posts.html
{% extends 'base.html' %}
{% load blog_tags %}

<title> {% block title %}My Blog{% endblock %}
</title>
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href=" {{ post.get_absolute_url}}" >{{ post.title }}</a>
        </h2>
        <p class="tags">Tags:
            {% for tags in post.tags.all %}
                {% if tag.slug %}
            <a href="{% url "posts:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
                {% endif %}
            {% endfor   %}
           </p>
        <p class="date">
        Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords:30|linebreaks }}



    {% endfor %}
    {% include "pagination.html" with page=posts %}

{% endblock %}

posts/templates/posts/search.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block title%}  Search {% endblock %}


{% block content %}
{% if query %}
    <h1>Posts Containing  "{{ query }}"</h1>

  <h3>
  {% with results.count as total_results %}
      Found {{ total_results }} result{{ total_results|pluralize}}

  {% endwith %}
  </h3>

    {% for post in results  %}
        <h4>
            <a href="{{ post.get_absolute_url }}">


                {{ post.title }}
            </a>

        </h4>

        {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
        <p>There are no results for your query</p>

    {% endfor %}
    <p>
        <a href="{% url "posts:post_search" %}">Search Again </a>
    </p>
    {% else %}
    <h1>Search for posts</h1>
    <form action="" method="get">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Search">
    </form>

{% endif %}
{% endblock %}

posts/templates/posts/share.html
{% extends 'base.html' %}


{% block title %} Share a Post     {% endblock %}

{% block content %}
{% if sent %}
<h1>Email successfully sent</h1>

<p>
 "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}
</p>
    {% else %}
    h1>Share "{{ post.title }}" by email</h1>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send Email">
    </form>
{% endif %}

{% endblock %}

templates/base.html
{% load blog_tags %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/app.css" %}">


</head>
<body >
<div id="content" >
    {% block content %}

{% endblock %}
</div>


<div id="sidebar">
    <h2>My Blog</h2>
{#    {% if tag %}#}
{#    <h2>Tags: "{{ tag.name }}"</h2>#}
{#    {% endif %}#}

    <p>This is my Blog.
        I've written {% total_posts %} posts so far
    </p>
<p>
    <a href="{% url "posts:post_feed" %}">
        Subscribe to my RSS feed
    </a>
</p>
    <h3>Latest Posts</h3>
    {% show_latest_posts 3 %}
    <h3>Most commented Posts</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
        {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% endfor %}
    </ul>
</div>

</body>



</html>

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        
        {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    
    {% endif %}
    </span>
</div>